name: Build and Publish TytoDB

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: [x86_64-unknown-linux-gnu, aarch64-unknown-linux-gnu]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: ${{ matrix.target }}
          cache: true # Enable caching for dependencies

      - name: Install cross
        run: cargo install cross

      - name: Build TytoDB
        run: cross build --release --target ${{ matrix.target }}

      - name: Package the binary
        run: |
          mkdir -p dist
          cp target/${{ matrix.target }}/release/tytodb dist/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tytodb-binary-${{ matrix.target }}
          path: dist/